export const MULTISIG_ABI = [
  "event Deposit(address indexed sender, uint256 amount, uint256 balance)",
  "event SubmitTransaction(address indexed owner, uint256 indexed txIndex, address indexed to, uint256 value, bytes data)",
  "event ConfirmTransaction(address indexed owner, uint256 indexed txIndex)",
  "event RevokeConfirmation(address indexed owner, uint256 indexed txIndex)",
  "event ExecuteTransaction(address indexed owner, uint256 indexed txIndex)",
  "event OwnerAdded(address indexed owner)",
  "event OwnerRemoved(address indexed owner)",
  "event RequirementChanged(uint256 required)",
  "function getOwners() view returns (address[])",
  "function getTransactionCount() view returns (uint256)",
  "function getTransaction(uint256 txIndex) view returns (address to, uint256 value, bytes data, bool executed, uint256 numConfirmations)",
  "function isOwner(address account) view returns (bool)",
  "function isConfirmed(uint256 txIndex, address owner) view returns (bool)",
  "function required() view returns (uint256)",
  "function getBalance() view returns (uint256)",
  "function submitTransaction(address to, uint256 value, bytes calldata data) returns (uint256 txIndex)",
  "function confirmTransaction(uint256 txIndex)",
  "function executeTransaction(uint256 txIndex)",
  "function revokeConfirmation(uint256 txIndex)",
  "function addOwner(address owner)",
  "function removeOwner(address owner)",
  "function changeRequirement(uint256 newRequired)",
];